---
version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6

  pre_build:
    commands:
      - printenv
      - echo "*** pre-build ***"
      - ruby --version
      - bundle install --path vendor/bundle

  build:
    commands:
      - echo "*** build ***"
      - zip -r ruby-lambda1.zip ruby-lambda1.rb vendor
      - aws lambda update-function-code --function-name ruby-lambda1 --zip-file fileb://ruby-lambda1.zip

  post_build:
    commands:
      - echo "*** post_build ***"

artifacts:
  files:
    - '**/*'

---