---
version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6

  pre_build:
    commands:
      - printenv
      - echo "*** pre-build ***"
      - ruby --version

  build:
    commands:
      - echo "*** build ***"
      - export DIR_NAME=lambda1
      - cd $DIR_NAME
      - bundle install --path vendor/bundle --without development
      - zip -r function.zip *.rb vendor
      - aws lambda update-function-code --function-name $DIR_NAME --zip-file fileb://function.zip
      - export DIR_NAME=lambda2
      - cd ../$DIR_NAME
      - bundle install --path vendor/bundle --without development
      - zip -r function.zip *.rb vendor
      - aws lambda update-function-code --function-name $DIR_NAME --zip-file fileb://function.zip
      
  post_build:
    commands:
      - echo "*** post_build ***"

artifacts:
  files:
    - '**/*'

---