---
version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6

  pre_build:
    commands:
      - printenv
      - echo "*** pre-build ***"
      - ruby --version

  build:
    commands:
      - echo "*** build ***"
      - cd lambda1
      - bundle install --path vendor/bundle --without development
      - export FUNCTION_NAME=ruby-lambda1
      - zip -r function.zip *.rb vendor
      - aws lambda create-function --function-name $FUNCTION_NAME --zip-file fileb://function.zip --handler $FUNCTION_NAME.lambda_handler --runtime ruby2.5 --role $LAMBDA_ROLE_ARN
      - cd ../lambda2
      - bundle install --path vendor/bundle --without development
      - export FUNCTION_NAME=ruby-lambda2
      - zip -r function.zip *.rb vendor
      - aws lambda create-function --function-name $FUNCTION_NAME --zip-file fileb://function.zip --handler $FUNCTION_NAME.lambda_handler --runtime ruby2.5 --role $LAMBDA_ROLE_ARN

  post_build:
    commands:
      - echo "*** post_build ***"

artifacts:
  files:
    - '**/*'

---