---
version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6

  pre_build:
    commands:
      - printenv
      - echo "*** pre-build ***"
      - ruby --version
      - bundle install --path vendor/bundle --without development

  build:
    commands:
      - echo "*** build ***"
      - zip -r function.zip *.rb vendor
      - aws lambda create-function --function-name ruby-lambda1 --zip-file fileb://function.zip --handler lambda_handler --runtime ruby2.6 --role $LAMBDA_ROLE_ARN

  post_build:
    commands:
      - echo "*** post_build ***"

artifacts:
  files:
    - '**/*'

---